import { createContext, useContext, useEffect, useState, ReactNode } from "react";

interface Dealership {
  id: number;
  name: string;
  subdomain: string;
  city?: string;
  province?: string;
  logo?: string;
  primaryColor?: string;
  secondaryColor?: string;
}

interface TenantContextType {
  isMarketingSite: boolean;
  isLoading: boolean;
  dealership: Dealership | null;
  subdomain: string | null;
  routingStatus: 'marketing' | 'tenant' | 'unknown-tenant';
}

const TenantContext = createContext<TenantContextType>({
  isMarketingSite: true,
  isLoading: true,
  dealership: null,
  subdomain: null,
  routingStatus: 'marketing',
});

export function useTenant() {
  return useContext(TenantContext);
}

const MARKETING_DOMAINS = [
  "lotview.ai",
  "www.lotview.ai",
  "lotview.onrender.com",
  "localhost",
  "127.0.0.1",
];

function isMarketingDomain(hostname: string): boolean {
  const lowerHostname = hostname.toLowerCase();
  
  if (MARKETING_DOMAINS.some(domain => lowerHostname === domain || lowerHostname.endsWith(`.replit.dev`) || lowerHostname.endsWith(`.replit.app`))) {
    const parts = lowerHostname.split('.');
    if (lowerHostname.endsWith('.replit.dev') || lowerHostname.endsWith('.replit.app')) {
      return parts.length <= 3;
    }
    if (lowerHostname === 'lotview.ai' || lowerHostname === 'www.lotview.ai') {
      return true;
    }
    return true;
  }
  
  return false;
}

function isReplitAutoGeneratedHost(hostname: string): boolean {
  const host = hostname.split(':')[0].toLowerCase();
  if (host.endsWith('.replit.dev') || host.endsWith('.repl.co') || host.endsWith('.replit.app')) {
    const parts = host.split('.');
    if (parts.length >= 3) {
      const subdomain = parts[0];
      if (subdomain.length > 20 && subdomain.includes('-')) {
        return true;
      }
    }
  }
  return false;
}

function extractSubdomain(hostname: string): string | null {
  const lowerHostname = hostname.toLowerCase();
  
  if (isReplitAutoGeneratedHost(lowerHostname)) {
    return null;
  }
  
  if (lowerHostname.endsWith('.lotview.ai')) {
    const subdomain = lowerHostname.replace('.lotview.ai', '');
    if (subdomain && subdomain !== 'www') {
      return subdomain;
    }
  }
  
  if (lowerHostname.endsWith('.replit.dev') || lowerHostname.endsWith('.replit.app')) {
    const parts = lowerHostname.split('.');
    if (parts.length > 3) {
      return parts[0];
    }
  }
  
  return null;
}

export function TenantProvider({ children }: { children: ReactNode }) {
  const [state, setState] = useState<TenantContextType>({
    isMarketingSite: true,
    isLoading: true,
    dealership: null,
    subdomain: null,
    routingStatus: 'marketing',
  });

  useEffect(() => {
    const hostname = window.location.hostname;
    const subdomain = extractSubdomain(hostname);
    const isDevelopment = hostname.endsWith('.replit.dev') || hostname.endsWith('.replit.app') || hostname === 'localhost' || hostname === '127.0.0.1';
    
    if (!subdomain && isMarketingDomain(hostname) && !isDevelopment) {
      setState({
        isMarketingSite: true,
        isLoading: false,
        dealership: null,
        subdomain: null,
        routingStatus: 'marketing',
      });
      return;
    }

    const url = new URL(window.location.href);
    const explicitDealershipId = url.searchParams.get('dealershipId');
    const explicitSubdomain = url.searchParams.get('subdomain');
    const requestedTenantKey = explicitSubdomain || subdomain || explicitDealershipId;
    const shouldFailClosed = Boolean(explicitSubdomain || subdomain || explicitDealershipId);

    const resolveUrl = explicitSubdomain
      ? `/api/tenancy/resolve?subdomain=${encodeURIComponent(explicitSubdomain)}`
      : subdomain
        ? `/api/tenancy/resolve?subdomain=${encodeURIComponent(subdomain)}`
        : explicitDealershipId
          ? `/api/tenancy/resolve?dealershipId=${encodeURIComponent(explicitDealershipId)}`
          : null;

    if (!resolveUrl) {
      setState({
        isMarketingSite: true,
        isLoading: false,
        dealership: null,
        subdomain: null,
        routingStatus: 'marketing',
      });
      return;
    }

    fetch(resolveUrl)
      .then(async (res) => {
        const data = await res.json().catch(() => null);
        return { ok: res.ok, data };
      })
      .then(({ ok, data }) => {
        if (ok && data?.dealership) {
          setState({
            isMarketingSite: false,
            isLoading: false,
            dealership: data.dealership,
            subdomain,
            routingStatus: 'tenant',
          });
          return;
        }

        if (shouldFailClosed && requestedTenantKey) {
          setState({
            isMarketingSite: false,
            isLoading: false,
            dealership: null,
            subdomain: explicitSubdomain || subdomain,
            routingStatus: 'unknown-tenant',
          });
          return;
        }

        setState({
          isMarketingSite: true,
          isLoading: false,
          dealership: null,
          subdomain: null,
          routingStatus: 'marketing',
        });
      })
      .catch(() => {
        if (shouldFailClosed && requestedTenantKey) {
          setState({
            isMarketingSite: false,
            isLoading: false,
            dealership: null,
            subdomain: explicitSubdomain || subdomain,
            routingStatus: 'unknown-tenant',
          });
          return;
        }

        setState({
          isMarketingSite: true,
          isLoading: false,
          dealership: null,
          subdomain: null,
          routingStatus: 'marketing',
        });
      });
  }, []);

  return (
    <TenantContext.Provider value={state}>
      {children}
    </TenantContext.Provider>
  );
}
