import { createContext, useContext, useEffect, useState, ReactNode } from "react";

interface Dealership {
  id: number;
  name: string;
  subdomain: string;
  city?: string;
  province?: string;
  logo?: string;
  primaryColor?: string;
  secondaryColor?: string;
}

interface TenantContextType {
  isMarketingSite: boolean;
  isLoading: boolean;
  dealership: Dealership | null;
  subdomain: string | null;
}

const TenantContext = createContext<TenantContextType>({
  isMarketingSite: true,
  isLoading: true,
  dealership: null,
  subdomain: null,
});

export function useTenant() {
  return useContext(TenantContext);
}

const MARKETING_DOMAINS = [
  "lotview.ai",
  "www.lotview.ai",
  "localhost",
  "127.0.0.1",
];

function isMarketingDomain(hostname: string): boolean {
  const lowerHostname = hostname.toLowerCase();
  
  if (MARKETING_DOMAINS.some(domain => lowerHostname === domain || lowerHostname.endsWith(`.replit.dev`) || lowerHostname.endsWith(`.replit.app`))) {
    const parts = lowerHostname.split('.');
    if (lowerHostname.endsWith('.replit.dev') || lowerHostname.endsWith('.replit.app')) {
      return parts.length <= 3;
    }
    if (lowerHostname === 'lotview.ai' || lowerHostname === 'www.lotview.ai') {
      return true;
    }
    return true;
  }
  
  return false;
}

function isReplitAutoGeneratedHost(hostname: string): boolean {
  const host = hostname.split(':')[0].toLowerCase();
  if (host.endsWith('.replit.dev') || host.endsWith('.repl.co') || host.endsWith('.replit.app')) {
    const parts = host.split('.');
    if (parts.length >= 3) {
      const subdomain = parts[0];
      if (subdomain.length > 20 && subdomain.includes('-')) {
        return true;
      }
    }
  }
  return false;
}

function extractSubdomain(hostname: string): string | null {
  const lowerHostname = hostname.toLowerCase();
  
  if (isReplitAutoGeneratedHost(lowerHostname)) {
    return null;
  }
  
  if (lowerHostname.endsWith('.lotview.ai')) {
    const subdomain = lowerHostname.replace('.lotview.ai', '');
    if (subdomain && subdomain !== 'www') {
      return subdomain;
    }
  }
  
  if (lowerHostname.endsWith('.replit.dev') || lowerHostname.endsWith('.replit.app')) {
    const parts = lowerHostname.split('.');
    if (parts.length > 3) {
      return parts[0];
    }
  }
  
  return null;
}

export function TenantProvider({ children }: { children: ReactNode }) {
  const [state, setState] = useState<TenantContextType>({
    isMarketingSite: true,
    isLoading: true,
    dealership: null,
    subdomain: null,
  });

  useEffect(() => {
    const hostname = window.location.hostname;
    const subdomain = extractSubdomain(hostname);
    const isDevelopment = hostname.endsWith('.replit.dev') || hostname.endsWith('.replit.app') || hostname === 'localhost' || hostname === '127.0.0.1';
    
    if (!subdomain && isMarketingDomain(hostname) && !isDevelopment) {
      setState({
        isMarketingSite: true,
        isLoading: false,
        dealership: null,
        subdomain: null,
      });
      return;
    }

    const resolveUrl = subdomain 
      ? `/api/tenancy/resolve?subdomain=${encodeURIComponent(subdomain)}`
      : `/api/tenancy/resolve?dealershipId=1`;

    fetch(resolveUrl)
      .then(res => res.json())
      .then(data => {
        if (data.dealership) {
          setState({
            isMarketingSite: false,
            isLoading: false,
            dealership: data.dealership,
            subdomain,
          });
        } else {
          setState({
            isMarketingSite: true,
            isLoading: false,
            dealership: null,
            subdomain: null,
          });
        }
      })
      .catch(() => {
        setState({
          isMarketingSite: true,
          isLoading: false,
          dealership: null,
          subdomain: null,
        });
      });
  }, []);

  return (
    <TenantContext.Provider value={state}>
      {children}
    </TenantContext.Provider>
  );
}
